@startuml
'https://plantuml.com/class-diagram

package creational_patterns{

    package singleton {

        class Parameters {

            - static final Parameters instance;
            - String loggedUsername;
            - String storeName;

            + {static} Parameters getInstance()
            + String getLoggedUsername()
            + void setLoggedUsername(String loggedUsername)
            + String getStoreName()
            + void setStoreName(String storeName)

        }

    }

}

@enduml
