@startuml
'https://plantuml.com/class-diagram

package creational_patterns{

    package factory_method {

        interface IService {
            String run()
            String cancel()
        }

        class ServiceAcquisition {
            + String run()
            + String cancel()
        }
        note top: Propositadamente não implementa\nIService, para testar depois

        class ServiceFactory {
            + {static} IService getService(String serviceName)
        }

        class ServiceProduction implements IService {
            + String run()
            + String cancel()
        }

        class ServiceSale implements IService {
            + String run()
            + String cancel()
        }

        class ServiceStocking implements IService {
            + String run()
            + String cancel()
        }

    }

}

@enduml
